#pragma config(Sensor, in1,    leftPoten,      sensorPotentiometer)
#pragma config(Sensor, in2,    rightPoten,     sensorPotentiometer)
#pragma config(Sensor, in3,    autonPoten,     sensorPotentiometer)
#pragma config(Sensor, dgtl1,  maxTouch,       sensorTouch)
#pragma config(Sensor, dgtl2,  minTouch,       sensorNone)
#pragma config(Motor,  port2,           SE,            tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           SW,            tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           NE,            tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           NW,            tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           LeftArm,       tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           RightArm,      tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,            ,             tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "mattlib.c"

//***************************************************************************//
//								 						VEX COMPETITION																 //
//***************************************************************************//

#pragma platform(VEX)
#pragma competitionControl(Competition)
#pragma autonomousDuration(15)
#pragma userControlDuration(105)

#include "Vex_Competition_Includes.c"   //Do not modify.

//***************************************************************************//

#define LX 	-vexRT[Ch4]
#define LY 	 vexRT[Ch3]
#define RX 	-vexRT[Ch1]

int autonDial = SensorValue[autonPoten];

void armMove(int power) {
	motor[LeftArm] 		= 	power;
	motor[RightArm] 	=  -power;
}

task drive();
task launch();

void placeholder() {
	mattlogo();
}

void pre_auton() {
	//program auton dial
}

task autonomous()	{
	
	autonDial = floor((SensorValue[autonPoten]) / 10);

	while(true) {
		if (autonDial >= 250) {
			placeholder(); //left
		}
		if (autonDial <= 249) {
			placeholder(); //right
		}

	}
}

task usercontrol()	{
	startTask(drive);
	startTask(launch);
}

task drive() {

	while (true) {
		motor[NW] =  LX - LY - RX;
		motor[NE] = -LX - LY - RX;
		motor[SW] = -LX + LY - RX;
		motor[SE] =  LX + LY - RX;
		wait1Msec(10);
	}

}

task launch() {

	bLCDBacklight = true;

	clearLCD();
	int potentiometer;

	while(true) {
		
		potentiometer = ((SensorValue[leftPoten] + SensorValue[rightPoten]) /2);
		displayLCDNumber(1, 0, potentiometer);
		
		autonDial = floor((SensorValue[autonPoten]) / 10);
		displayLCDNumber(0, 0, autonDial);


		//if(potentiometer >= 1001 && potentiometer <= 2351) {

		if(vexRT[Btn5U] == true) {
			armMove(90);
		}
		else if(vexRT[Btn5D] == true) {
			armMove(-50);
		}
		else {
			armMove(0);
		}

		if(vexRT[Btn6U] == true) {
			while(potentiometer > 1001 && potentiometer < 2500) {
				potentiometer = ((SensorValue[leftPoten] + SensorValue[rightPoten]) /2);
				displayLCDNumber(1, 0, potentiometer);
				armMove(100);
			}
			armMove(0);
		}

		wait1Msec(10);

	}

}
